

# Laitteisto





# a) Tee yksinkertainen esimerkkiohjelma Djangolla

Aloitin tehtävän suorittamisen avaamalla Teron ohjeet: https://terokarvinen.com/2022/django-instant-crm-tutorial/  ja aloin tekemään tehtävää niiden mukaisesti.

Ensimmäisenä avasin linux - virtuaalikoneen ja sieltä komentokehoitteen ja päivitin apt-getin.

![image](https://github.com/user-attachments/assets/5325df16-b8c5-404d-a94b-bc2c3e7a7914)

Seuraavaksi asensin ja loin ohjeiden mukaisesti uuden virtualenv:in, jotta voin asentaa Python paketteja, kuten nyt tässä seuraavaksi Djangon.

![image](https://github.com/user-attachments/assets/8818646a-c076-4aef-a4f7-0c7552b62d9d)

![image](https://github.com/user-attachments/assets/18a05689-6111-49b4-b9ca-20fbf262476b)

Seuraavaksi aktivoin äsken asennettun virtuaaliympäristön:

![image](https://github.com/user-attachments/assets/fc399aa9-afca-49b0-a196-c291ba655399)

Testasin, että asennnus menee virtuaali ympäristöön.

![image](https://github.com/user-attachments/assets/23dab1aa-210a-4c8e-98e0-96d71171bbf9)

Seuraavaksi kirjoitin asennustietoja tekstitiedostoon, jotta voidaan varmistaa ettei asennukseen tule kirjoitusvirheitä ja sen mukana viruksia yms.

    sudo apt-get install micro

Koneelta löytyiksin uusin micro jo valmiiksi:

![image](https://github.com/user-attachments/assets/acc52abd-6f20-4b2a-954f-babab8e6dab1)

Seuraavaksi kirjoitin asennustiedoston ja asensin djangon

![image](https://github.com/user-attachments/assets/d21d3e0e-a7f2-43af-b27e-7e33b0b36cbc)

Sain seuraavan virheilmoituksen:

exit
![image](https://github.com/user-attachments/assets/650043d9-7a6f-421f-9b30-3b0cb3f177a1)

Kokeilin seuraavaksi toimisiko tämä, jos otan yhteyden virtuaalikoneeseeni ja teen samat asetukset kuin virtuaalikoneelle aiemmin:

![image](https://github.com/user-attachments/assets/b04898f8-fb82-448c-bec9-6e5218ff954c)

![image](https://github.com/user-attachments/assets/f45f20a3-e38c-4c1b-a806-3e7142936ed4)

Nyt kone latas ainakin todella paljon pidempään erinäisiä tietoja, kuin virtuaalikoneella, ku ajoin komennon:

    sudo apt-get -y install virtualenv

![image](https://github.com/user-attachments/assets/742fdf00-3e24-4368-9815-c5a2fc575fa8)

![image](https://github.com/user-attachments/assets/deed4381-0c84-45bc-a2cf-ff6a89b1e7f2)

![image](https://github.com/user-attachments/assets/f7a608bd-6b69-4d52-a58f-1c8d47ecbc9f)

![image](https://github.com/user-attachments/assets/8422c6ec-0b6e-45fa-bd47-ab59e1ac5769)

Noniin, nyt alkoi tapahtua enemmän asioita ja asennus käynnistyi:

![image](https://github.com/user-attachments/assets/f9fde12d-d1d8-401f-9f54-c9a9e1d85d23)

Seuraavaksi tarkistin, että minkä version djangosta juuri asensin:

    django-admin --version

![image](https://github.com/user-attachments/assets/e5b8a6af-6a1a-4bce-9a20-aa672c9dc1a3)

Seuraavaksi aloitin projektin:

![image](https://github.com/user-attachments/assets/97ad7568-84a5-4fb7-9486-7e8cba2c08d6)

ja testasin sitä:

![image](https://github.com/user-attachments/assets/1dac446e-a0f5-497e-bc01-f5a5d83c059a)

Tajusin tässä kohtaa, että en saa tuota sivustoa auki selaimessa, koska täällä ei sellaista ole. Joten palasin takaisin selvittämään syytä, miksi tämä ei toiminut virtuaalikoneella.

Avasin komentokehoitteen ja kokeilin komentoa curl iltalehti.fi

![image](https://github.com/user-attachments/assets/67e19ab5-0fff-450d-bc4b-fdc6835eebf5)

Sain vastauksen: couldnt resolve host: iltalehti.fi, joten ongelma viittaa nimenselvitykseen. Seuraavaksi katsoin nimipalvelimet ja lisäsin sinne googlen-palvelimen 8.8.8.8 ja tallensin.

![image](https://github.com/user-attachments/assets/5d1ad665-16c3-4524-b03d-1fcdb00922e3)

Edelleen oli sama ongelma..

Kokeilin muokata dns-listaa tuloksetta, koska ping ei edelleenkään toiminut.

![image](https://github.com/user-attachments/assets/16d3cf65-2810-418a-9581-c3befab44688

Sitten kokeilin uudelleenkäynnistää NetworkManagerin komennolla:

        sudo systemctl restart NetworkManager

ja sain seuraavanlaisen ponnahdusikkunan näkyviin:

![image](https://github.com/user-attachments/assets/286e64b8-ed5b-4bb9-8a42-7290e94be2ec)

Nyt vaikutti jo lupaavammalta, testasin siis jälleen pingiä ja nyt nimenselvitys näytti toimivan vihdoikin!

![image](https://github.com/user-attachments/assets/ce74699b-f053-4a79-ac34-2dc1cb41c99e)

Sitten vaan tein tutuksi tulleet komennot ja yritin nyt asentaa djangon uudelleen:

Vihdoinkin asennus käynnistyi:

![image](https://github.com/user-attachments/assets/e7cbe82a-421c-4569-b9ee-df1cd54b6b4f)

Tarkistin vielä version ja loin uuden projektin.

![image](https://github.com/user-attachments/assets/5b931e08-c504-4cc6-921e-5a12731e2174)

Sitten siirryin kokeiluvaiheeseen ja käynnistin testiympäristön palvelimen ja yritin siirtyä sinne selaimella.

![image](https://github.com/user-attachments/assets/d6bce731-1b09-447a-8232-dfc961307a7a)

ja vihdoin se toimii...

![image](https://github.com/user-attachments/assets/e7d4f4ae-281f-461b-a4ed-851df9cdeac7)

Seuraavaksi vuorossa oli luoda admin-portaali tänne: URL. http://127.0.0.1:8000/admin/

Päivitin tietovarastot, joista ylempänä tuli virheilmoitus.

![image](https://github.com/user-attachments/assets/152df536-e46f-4f32-92ea-fa375c3776ba)

Seuraavaksi aloin luomaan käyttäjää ja asensin aluksi salasanageneraattorin.

![image](https://github.com/user-attachments/assets/3a0c5650-2c62-4597-a8e0-50c0660e2d74)

![image](https://github.com/user-attachments/assets/fd3c388d-ee78-444f-8ce7-77be0fa7c4a3)

Ja noin, nyt on admin käyttis luotuna ja seuraavaksi oli vuorossa kokeilla nettiselaimessa, että toimiiko sen oikein ja ei toiminut koko projekti tuntui kadonneen. 

( Updated 4.10. ) Yritin kaikenlaista usemman kerran kunnes päädyin pitämään pidemmän tauon tästä aiheesta ja sen jälkee luomaan kokonaan uuden virtuaalikoneen ja asensin ihan kaikki alusta alkaen uudelleen.

![image](https://github.com/user-attachments/assets/a02867d5-f1db-41f7-9244-87403943f20d)

Nyt admin sivu näkyi, ja oli aika kokeilla tehdä tuo tietovarastojen päivitys uudelleen, jonka vuoksi viimeksi kaikki meni ihan sekaisin.

![image](https://github.com/user-attachments/assets/1f253b04-952e-4a9f-974a-8c1ddd1bba9a)

Paljon ok merkintöjä, joten ehkä migraatio onnistui. Jatkoin seuraavaksi asentamall salasanageneraattorin, lisäämällä käyttäjän ja sen jälkeen käynnistin palvelimen uusiksi.

![image](https://github.com/user-attachments/assets/c036588d-3e8d-4538-9e32-0f0d9032f648)

![image](https://github.com/user-attachments/assets/a63d1281-c9f6-43a3-9ad4-1d58470d8409)

![image](https://github.com/user-attachments/assets/1901acd1-131c-4f99-90b1-cfc883c2538d)

Vihdoinkin pääsin sisälle testiympäristöön :)

![image](https://github.com/user-attachments/assets/4f48ca23-13fd-4e0d-9308-d93e3493f29a)

Nyt vain jatkoin opettajan ohjeiden mukaisesti ja loin seuraavaksi uuden käyttäjän, joka voi muokata sisälötä webbiliittymän kautta.

Loin käyttäjän nimeltä web_admin ja annoin seuraavat oikeudet: staff ja superuser

![image](https://github.com/user-attachments/assets/d953f3e6-4a57-47ab-a9fa-7bc6108c6df3)

Seuraavaksi kirjauduin ulos ja sitten äsken luoduilla tunnuksilla sisään.

![image](https://github.com/user-attachments/assets/d158a886-5bda-4ecf-b5bf-6560f0314f4f)

web_admin pääsi sisään ja pystyi muokkaamaan asioita.

![image](https://github.com/user-attachments/assets/ec94bf6d-17bf-4513-8394-0a6e3ce7d206)

![image](https://github.com/user-attachments/assets/65d02583-9bc1-455e-afc8-df8d15e27a4e)

Kun kaikki oli tältä osin kunnossa, niin aloin seuraavaksi ohjeiden mukaisesti luomaan asiakastietokantaa.

![image](https://github.com/user-attachments/assets/616e596e-35dc-4efb-8c7c-d4c2c50dbf82)

![image](https://github.com/user-attachments/assets/d6664b89-ad14-4679-a823-91afb0ddd438)

Loin seuraavaksi mallin ( Customer-luokka ). Tästä pitäisi syntyä webbiliittymään taulukko: Customer.

![image](https://github.com/user-attachments/assets/084d2b61-a847-4db1-aa78-f1a8e7a2a121)

Ajoin sitten nuo migraatiokomennot:

![image](https://github.com/user-attachments/assets/989b392d-2899-496c-8282-d1f0d089ede6)

Sitten rekisteröin crm tietokannan, jotta se näkyisi admin-puolella.

![image](https://github.com/user-attachments/assets/43af9836-89f2-4abe-b35b-58a58fd236e3)

![image](https://github.com/user-attachments/assets/089c1dfe-9d46-4fbc-9dcb-387e66b03f69)

Käynnistin myös serverin uudelleen komennolla:

        ./manage.py runsrver

Sitten kirjauduin uudelleen admin-portaaliin:(http://127.0.0.1:8000/admin/), johon oli ilmestynyt CRM-luokka.

![image](https://github.com/user-attachments/assets/1507883e-9370-4110-bf48-6584a67d1cce)

Lisäsin asiakkaita ja poistin ne.

![image](https://github.com/user-attachments/assets/b7fea131-add4-4b61-be7c-15205d885286)

![image](https://github.com/user-attachments/assets/6d38e5ed-4c08-449b-93d6-86558fb1e21e)

![image](https://github.com/user-attachments/assets/61ecfb32-7fe9-4c9b-bb91-d0a5301d0cc4)

Sitten muokattiin crm-mallia, niin että se näyttäisi asiakkaiden nimet, eikä vaan jotain geneerisiä sanoja ja oma numero sulkujen perässä.

![image](https://github.com/user-attachments/assets/518b3033-3ce5-49f5-8cfa-89e08bf03e8e)

Serveri käyntiin, sisäänkirjautuminen ja katsotaan, että muuttuiko mikään.

![image](https://github.com/user-attachments/assets/507a52db-bec8-40bb-b2a4-d11d41b4fb5c)

Ja näin, asiakkailla on nyt ihan omat nimet, eikä vain numeroita:

![image](https://github.com/user-attachments/assets/70864fda-5f25-45c9-a8cc-0da0314efcf2)
















































# b) Tee Djangon tuotantotyyppinen asennus

